export const data = [
  {
    id: "62c5fc13eed63411f9b1dff4",
    index: 0,
    guid: "4df43c62-a2f2-4db5-837a-5054437d5e12",
    isActive: false,
    balance: "$2,213.15",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGlMrO77Rk7jrsLQuVIt4SvlZJ38gFja_BLQ&usqp=CAU",
    age: 33,
    eyeColor: "blue",
    name: "Tami Moody",
    price: 25.11,
    gender: "female",
    company: "ISOLOGIX",
    email: "tamimoody@isologix.com",
    phone: "+1 (876) 575-3254",
    address: "244 Sharon Street, Wacissa, Mississippi, 6538",
    about:
      "Fugiat ipsum duis nostrud ad ea veniam in. Sit cillum ad quis qui dolore in qui deserunt in consequat ullamco ad. Consequat quis enim laborum non.\r\n",
    registered: "2016-04-01T02:13:08 -03:00",
    latitude: 37.78411,
    longitude: -111.497594,
    tags: ["Lorem", "ea", "labore", "labore", "sunt", "qui", "nisi"],
    friends: [
      {
        id: 0,
        name: "Crane Burks",
      },
      {
        id: 1,
        name: "Bates Baldwin",
      },
      {
        id: 2,
        name: "Charity Vaughan",
      },
    ],
    greeting: "Hello, Tami Moody! You have 8 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "62c5fc137f28acc40ca1d715",
    index: 1,
    guid: "73c1a027-fa2c-4bb7-9b41-230a9bb3e0ee",
    isActive: false,
    balance: "$3,871.18",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoYdM_Wd2rGPyFjPTTAnBobm3UR-oQtQnU9g&usqp=CAU",
    age: 23,
    eyeColor: "green",
    name: "Freida Sanchez",
    price: 64.32,
    gender: "female",
    company: "ZENTIME",
    email: "freidasanchez@zentime.com",
    phone: "+1 (944) 583-3917",
    address: "294 Eastern Parkway, Detroit, Georgia, 9414",
    about:
      "Proident ea cillum elit velit irure eu aute nisi irure. Consectetur laboris pariatur voluptate minim sint. Amet tempor laborum aute quis anim irure magna. Excepteur duis dolore fugiat proident. Qui culpa velit irure enim ex aliqua laboris nostrud proident consectetur consequat commodo. Proident commodo elit id exercitation consequat quis consectetur incididunt fugiat velit in est tempor. Anim Lorem adipisicing exercitation velit tempor aute cupidatat pariatur labore consectetur deserunt sit sunt minim.\r\n",
    registered: "2016-05-31T04:25:17 -03:00",
    latitude: 9.64991,
    longitude: -84.141134,
    tags: ["cupidatat", "officia", "et", "eu", "sunt", "minim", "fugiat"],
    friends: [
      {
        id: 0,
        name: "Reva Dennis",
      },
      {
        id: 1,
        name: "Blake Winters",
      },
      {
        id: 2,
        name: "Krista Tanner",
      },
    ],
    greeting: "Hello, Freida Sanchez! You have 3 unread messages.",
    favoriteFruit: "strawberry",
  },
  {
    id: "62c5fc136fed73462e4d0dff",
    index: 2,
    guid: "9b828245-104c-4e47-844f-2867a31f1230",
    isActive: true,
    balance: "$3,477.64",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7GufDadVkFOdnWSzW9Gx1yg-SlRVrG29iIg&usqp=CAU",
    age: 27,
    eyeColor: "blue",
    name: "Conway Horne",
    price: 65.45,
    gender: "male",
    company: "TERASCAPE",
    email: "conwayhorne@terascape.com",
    phone: "+1 (918) 587-3528",
    address: "492 Oak Street, Harviell, Ohio, 3678",
    about:
      "Nostrud consectetur qui voluptate aliqua exercitation eiusmod. Mollit ullamco duis nisi aliqua incididunt. Est minim eiusmod nostrud ad enim exercitation elit tempor sit. Sunt anim aliquip aute ullamco. Fugiat duis magna voluptate labore voluptate. Ipsum duis ipsum cupidatat consectetur occaecat tempor officia qui magna eu consequat. Occaecat labore sit enim consequat fugiat excepteur culpa exercitation non dolore id.\r\n",
    registered: "2016-08-10T11:22:26 -03:00",
    latitude: 48.752946,
    longitude: -125.172487,
    tags: ["nostrud", "non", "enim", "consectetur", "est", "dolore", "qui"],
    friends: [
      {
        id: 0,
        name: "Terrie Vinson",
      },
      {
        id: 1,
        name: "Lakeisha Mathews",
      },
      {
        id: 2,
        name: "Rhoda Bernard",
      },
    ],
    greeting: "Hello, Conway Horne! You have 3 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "62c5fc13d9526f9ba9fa2b79",
    index: 3,
    guid: "5ec2c6b7-fb39-4824-b5cf-a0c8836ea6ab",
    isActive: false,
    balance: "$3,192.09",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk7tDxoOZ_MF1x3kE2JGzBZ1eZdpxbvThEHQ&usqp=CAU",
    age: 20,
    eyeColor: "green",
    name: "Jolene Lynn",
    price: 52.54,
    gender: "female",
    company: "SPACEWAX",
    email: "jolenelynn@spacewax.com",
    phone: "+1 (848) 464-2339",
    address: "522 Willoughby Street, Islandia, Idaho, 9554",
    about:
      "Ea et anim labore nisi laboris. Esse esse irure aute et nisi non nulla incididunt consectetur. Proident ipsum duis ea mollit. Pariatur irure ex sint esse exercitation cillum nulla duis eu occaecat aliquip consequat. Consequat excepteur reprehenderit anim laboris amet aliquip laborum officia ut sunt elit in ea. Ullamco aliqua adipisicing fugiat non id ad.\r\n",
    registered: "2014-06-15T01:53:30 -03:00",
    latitude: -70.871558,
    longitude: -144.647969,
    tags: ["consequat", "occaecat", "do", "nulla", "ex", "do", "do"],
    friends: [
      {
        id: 0,
        name: "Cooke England",
      },
      {
        id: 1,
        name: "Leah Dickerson",
      },
      {
        id: 2,
        name: "Jayne Robles",
      },
    ],
    greeting: "Hello, Jolene Lynn! You have 1 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "62c5fc13da84f5ff391fc82c",
    index: 4,
    guid: "a224941e-b492-4089-8c84-f5f34892c7c0",
    isActive: true,
    balance: "$2,752.17",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSjNB9fjChOh4R5XAajy9B0FrCehkKgPCRsUg&usqp=CAU",
    age: 30,
    eyeColor: "brown",
    name: "Lori Dejesus",
    price: 53.55,
    gender: "female",
    company: "DIGIAL",
    email: "loridejesus@digial.com",
    phone: "+1 (828) 552-2476",
    address: "649 Vanderbilt Avenue, Suitland, Northern Mariana Islands, 3123",
    about:
      "Culpa elit aliquip exercitation tempor ex aliqua magna commodo culpa sit laboris. Tempor laborum mollit adipisicing veniam amet duis laboris nostrud pariatur fugiat voluptate sit est. Dolore ex pariatur ipsum voluptate amet. Adipisicing occaecat pariatur veniam nisi. Proident ad anim magna duis quis irure enim anim tempor elit. Consectetur id Lorem mollit in. Tempor exercitation proident occaecat sunt ut tempor laboris.\r\n",
    registered: "2015-03-11T04:49:12 -02:00",
    latitude: 33.581988,
    longitude: 19.091062,
    tags: ["ad", "proident", "et", "sit", "do", "pariatur", "nostrud"],
    friends: [
      {
        id: 0,
        name: "Chris Bentley",
      },
      {
        id: 1,
        name: "Hyde Dunlap",
      },
      {
        id: 2,
        name: "Jo Booker",
      },
    ],
    greeting: "Hello, Lori Dejesus! You have 2 unread messages.",
    favoriteFruit: "banana",
  },
  {
    id: "62c5fc14bab448f2c1864cd3",
    index: 5,
    guid: "0f8d6e14-1568-4bd4-a3eb-ab3c31b9f6a6",
    isActive: false,
    balance: "$3,001.81",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbhexunBo97hQ25UZOF8cuMYu2uSrlbMShRQ&usqp=CAU",
    age: 40,
    eyeColor: "brown",
    name: "Kris Rosa",
    price: 34.23,
    gender: "female",
    company: "COMFIRM",
    email: "krisrosa@comfirm.com",
    phone: "+1 (931) 534-2122",
    address: "163 Roder Avenue, Rodanthe, Oklahoma, 5696",
    about:
      "Veniam enim sint ex enim esse. In Lorem consectetur voluptate ea est aliqua veniam esse labore culpa consectetur ullamco. Consectetur ipsum adipisicing ut deserunt aliquip elit id qui sit occaecat eu elit. Cillum fugiat eu aute officia nisi Lorem in aute velit ad officia sunt amet. Officia amet consequat ullamco sint deserunt cillum. Irure sint minim ullamco est ad pariatur culpa. Ex Lorem commodo laboris laborum exercitation id.\r\n",
    registered: "2017-12-04T10:22:28 -03:00",
    latitude: -54.475168,
    longitude: 135.048007,
    tags: ["elit", "enim", "non", "duis", "tempor", "anim", "sunt"],
    friends: [
      {
        id: 0,
        name: "Earnestine Castillo",
      },
      {
        id: 1,
        name: "Zelma Mcmillan",
      },
      {
        id: 2,
        name: "Misty Butler",
      },
    ],
    greeting: "Hello, Kris Rosa! You have 8 unread messages.",
    favoriteFruit: "apple",
  },
  {
    id: "62c5fc1400460f9376c58cf4",
    index: 6,
    guid: "6088b997-7b99-4d6c-899e-72b24f3330e1",
    isActive: true,
    balance: "$1,496.07",
    picture:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSpqKuF2AeeJZ0y7QhH2Ggd9LgBNGFazuwSg&usqp=CAU",
    age: 30,
    eyeColor: "blue",
    name: "Bonner Zamora",
    price: 14.23,
    gender: "male",
    company: "XURBAN",
    email: "bonnerzamora@xurban.com",
    phone: "+1 (809) 531-2360",
    address: "844 Fay Court, Dellview, North Carolina, 7020",
    about:
      "Occaecat eu elit culpa Lorem commodo sint adipisicing sunt incididunt voluptate consequat irure aliqua. Et non tempor enim aute amet incididunt. Occaecat do voluptate officia mollit eu esse laboris labore anim deserunt aliqua dolor. Pariatur anim ipsum occaecat laborum reprehenderit eu ut aute elit labore consequat consequat qui. Excepteur amet dolor dolore aliqua et ullamco laborum sunt culpa culpa magna elit. Laborum nisi cillum irure dolore nisi eu quis cupidatat minim irure ea aliqua.\r\n",
    registered: "2015-12-10T11:10:43 -02:00",
    latitude: 40.658266,
    longitude: 144.522889,
    tags: [
      "consectetur",
      "exercitation",
      "quis",
      "cupidatat",
      "do",
      "anim",
      "esse",
    ],
    friends: [
      {
        id: 0,
        name: "Compton Schultz",
      },
      {
        id: 1,
        name: "Porter Parker",
      },
      {
        id: 2,
        name: "Meyers Summers",
      },
    ],
    greeting: "Hello, Bonner Zamora! You have 2 unread messages.",
    favoriteFruit: "banana",
  },
];
